### ISSUE TITLE
bad contrast for highlighted strings 

### ISSUE THREAD

**Issue by ccheney** [n8rzz/ss-octopus#1]
![screen shot 2018-08-01 at 12 21 14 pm](https://user-images.githubusercontent.com/302437/43537651-86093d4c-9585-11e8-8c3d-16c50ee3bc55.png)
![screen shot 2018-08-01 at 12 21 30 pm](https://user-images.githubusercontent.com/302437/43537652-861852fa-9585-11e8-90a2-9fb8d28ce9b2.png)

**Comment by n8rzz** [comment]
@ccheney how did you get the orange color in the second screenshot?  was that a direct highlight, a secondary highlight or something else?

**Comment by ccheney** [comment]
That’s from a project search: cmd+shift+f

**Comment by n8rzz** [comment]
find value highlight:

<img width="296" alt="screen shot 2018-08-03 at 7 35 57 am" src="https://user-images.githubusercontent.com/3325985/43643161-f12cf576-96ef-11e8-95d3-1c656b1bbfc9.png">
